[build]
  command = "npm run build"
  publish = ".next" 

# Keep all these sections below
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"